### ISSUE TITLE
ImportError: cannot import name '_dios_signal' from 'athena_signal'

### ISSUE THREAD

**Issue by iiicp** [athena-team/athena-signal#4]
python3 examples/athena_signal_test.py  succeeded
But in the interactive environment of Python3, the following error occurs

from athena_signal.dios_ssp_api import athena_signal_process
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxxx/athena-signal/athena_signal/__init__.py", line 18, in <module>
    from athena_signal import dios_ssp_api
  File "/Users/xxxx/athena-signal/athena_signal/dios_ssp_api.py", line 19, in <module>
    from athena_signal.dios_signal import dios_ssp_v1
  File "/Users/xxxx/athena-signal/athena_signal/diossignal.py", line 13, in <module>
    from . import _dios_signal
ImportError: cannot import name '_dios_signal' from 'athena_signal' (/Users/xxxx/athena-signal/athena_signal/__init__.py)

**Comment by jiashihuigithub** [comment]
请问您是怎么解决的？

**Comment by caihaoran-00** [comment]
您好，我也遇到了这个问题，请问您解决了嘛，是怎么解决的呢
